// fucntion to coppy text fro myDiv to clipboard
function copyToClipboard(elementId) {
    var aux = document.createElement("input");
    aux.setAttribute("value", document.getElementById("myDiv").innerText);
    document.body.appendChild(aux);
    aux.select();
    document.execCommand("copy");
    document.body.removeChild(aux);
    window.alert("Copied ✔")
}
document.onkeydown = function (e) {
    if (event.keyCode == 123) {
      return false;
    }
    if (e.ctrlKey && e.shiftKey && e.keyCode == "I".charCodeAt(0)) {
      return false;
    }
    if (e.ctrlKey && e.shiftKey && e.keyCode == "C".charCodeAt(0)) {
      return false;
    }
    if (e.ctrlKey && e.shiftKey && e.keyCode == "J".charCodeAt(0)) {
      return false;
    }
    if (e.ctrlKey && e.keyCode == "U".charCodeAt(0)) {
      return false;
    }
};
document.addEventListener("contextmenu", (event) => event.preventDefault());
const strings = ["[me != me]. [me += you].",
"A life without you, would be like a computer without an OS.",
"Anonymity makes me even more handsome.","Our relationship is like a mouse it just clicks",
"Are you a computer keyboard? Because you're my type.",
"Are you a computer whiz… it seems you know how to turn my software to hardware.",
"Are you a double? The thought of you always floats inside my head.",
"Are you an angel, because your texture mapping is divine!",
"Are you an applet? You make me feel all GUI (gooey) inside.",
"Are you an exception? Let me catch you.",
"Are you my driver? Because you make my life worthwhile.",
"Are you sitting on the F5 key? Cause your ass is refreshing.",
"Are your pants a compressed file? Because I'd love to unzip them!",
"Baby are you a motherboard?, Cause I'd RAM you all night long.",
"Baby you know this junk isn't USB2.0..it's firewire!",
"Baby you must be Google Glasses, because you augment my reality",
"Baby you're so cute you made my page 404.","What do you call a pickup line from a software developer? A pull request",
"Baby, if they made you in C, you would have a pointer to my heart.",
"Baby, if they made you in Java, you'd be the object of my desire.",
"Baby, let's configure our hard drives in master and slave position.",
"Baby, there is no part of my body that is Micro or Soft",
"Baby, you make my floppy disk turn into a hard drive",
"Baby, you overclock my processor.",
"Be the hard drive of my dreams.",
"Before you, I was a PC without a power outlet.",
"Can I stick my USB drive in your USB port?",
"Can you be my ActionListener? That way you notice everything that I do.",
"Can you be my private variable? I want to be the only one with access to you.",
"Come to my 127.0.0.1 and I'll give you sudo access.",
"Computer techs have skilled fingers if you know what I mean.",
"Could I have your I.P.?",
"Do u like me? Text '1' for 'Yes,' '2' for 'No.",
"Do you think we can make it a step more serious and disable network sharing?",
"Don't worry honey, they call it my dual-channel RAM.",
"Don't worry, the first couple of times it's always Abort, Retry, Fail.",
"Every once and a while two numbers meet, link, and become forever binary.",
"Girl, are you Wi-Fi? Cuz im feeling the connection!",
"Girl, you are an A++.",
"Girl, you are hotter than the bottom of my laptop.",
"Here's my number: 0011 0011 1011 0001 0010 1000 0101",
"Hey baby, did you know I am wearing a C-String?",
"Hey baby, I'm a power source, and you're the kind of resistor I'd like to deliver my load to.",
"Hey Baby, Let me hack your kernel.",
"Hey baby, lets turn off our firewalls and connect our Ethernet cable.",
"Hey cutie! I have a processor, and if you have an empty slot on your motherboard.",
"Hey, how 'bout I take off your cover and insert a bigger CPU.",
"How about we do a little peer-to-peer saliva swapping?",
"How about we go home and you handle my exception?",
"How'd you like to come to MySpace so I can Twitter you with my Yahoo until I Google on your Facebook?",
"I am a Boolean method whose love will always return true.",
"I am a Buffered Reader. You input meaning into my life.",
"I am the field attribute in your class: I can't exist unless you do.",
"I CAN HAS DA NASTY WIT U?",
"I didn't mean to ogle you, but I'd sure like to Google you.",
"I googled your name earlier... I clicked on 'I'm Feeling Lucky.'",
"I hope you're an ISO file, because I'd like to mount you.",
"I must be using Apple maps, because I keep getting lost in your eyes.",
"I need to hop over to Facebook for a second to change my status to smitten.",
"I output gibberish as you tap my keypad.",
"I think we should increase our bandwidth.",
"I think you could be an integral part of my project life cycle.",
"I think you're my compiler. My life wouldn't start without you.",
"I want all of our functions to be read/write.",
"I was hoping you wouldn't block my pop-up.",
"I wish to uncompress you over *all* my disk space.",
"I wish you were Broadband, so I could get high-speed access.",
"I wish you were DSL so I could get high speed access.",
"I would love to stick my pins into your sockets.",
"I'd ask if you come here often, but I already stalk you on FourSquare.",
"I'd get a T3 to watch your streaming video.",
"I'd like to play on your laptop.",
"I'd switch to a Iphone for you.",
"I'd switch to emacs for you.",
"I'll always have cache for you.",
"I'll bet my hard drive is the biggest you've ever seen.",
"I'll have to try again tomorrow, because you've already exceeded my bandwidth.",
"I'm definitely in the range of your hotspot. How about you let me connect and get full access.",
"I'm overheating because you're stuck in my head like an infinite loop.",
"I've fully rebooted from my last relationship.",
"If I was an operating system, your process would have top priority.",
"If I were a method, you must be my parameter, because I will always need you.",
"If I were an operating system, your process would be real-time priority.",
"If we were connected on LinkedIn, I'd endorse you all night long.",
"If you ever need to get rid of a trojan, don't hesitate to call me!",
"If you have an empty slot, I have the card to fill it.",
"If you were a part of my domain, we could share cookies.",
"If you were a USB Port I'd stick my jump drive into you.",
"If you were a web browser, you'd be called a Fire-foxy lady",
"If you were an eBay auction, I'd totally 'buy it now'.",
"If you were an ISP I'd dial you all day long.",
"If you won't let me buy you a drink, at least let me fix your laptop.",
"Im not staring, Im stuck in a loop. (Logic: while (girl=hot, look))",
"Is your name Google? Because you have everything I've been searching for.",
"Is your name Wi-fi? Because I'm really feeling a connection.",
"Is your network encrypted? Im looking to hack.",
"Isn't your e-mail address beautifulgirl@mydreams.com?",
"Let's interface our hardware.",
"Let's just cut to the chase, I wanna hotsync your PDA.",
"Living with you would be like living in a virtual reality.",
"Mind if I run a sniffer to see if your ports are open?",
"Most people say women are NP-complete, but if I get you into bed, I can solve you in polynomial time!",
"My 'up-time' is better than BSD.",
"My attraction for you is stronger than the magnetic forces inside of my hard disk.",
"My love for you comes with no strings attached.",
"My love for you is a constant variable: unupdatable and unchangeable.",
"My main method is 'public love iLoveYou().'",
"My name is #####, and I speak Klingon.",
"My servers never go down... but I do!",
"2Need me to unzip your files?",
"Nice Set of Floppies!",
"No GPU in the world could make you look hotter than you already are.",
"No kinky Windows stuff.",
"No matter how I sort things, you'll always be first.",
"No, that's not a iphone in my pants, but thanks for noticing.",
"No, that's not a Logitech MX-100 in my pants, but thanks for noticing.",
"No, that's not an iPod mini in my pocket. I'm just happy to see you.",
"Nobody turns me on from a cold boot like you.",
"Oh little processer of my desire!",
"Oh you still like Laptops, the you can put yo lap on top of my dick",
"Oh, you found out about my backups, didn't you?",
"Our Love Routines link perfectly.",
"Phone for you, I think it's your motherboard.",
"Press any key to continue.",
"Public class Your World extends My World.",
"Roses are #FF0000, violets are #0000FF. All my base are belong to you.",
"There is no cache, lets go straight to the hard drive.",
"Trust me, I'm user friendly.",
"Want to come see my HARD Disk? I promise it isn't 3.5 inches and it ain't floppy.",
"Want to see my HARD Disk? I promise it isn't 3.5 inches and it ain't floppy.",
"Want to see my Red Hat?",
"We are an aggregation of classes: one cannot exist without the other.",
"We can make beautiful .wav files together.",
"WebMD says your love is contagious.",
"Well, if that's how you feel, I guess it's time to upgrade.",
"Well, now you've gone and killed my process.",
"What's a nice girl like you doing in a chat room like this?",
"What's a nice girl like you doing in a chatroom like this?",
"Where's the 'like' button for that smile?",
"while(myBAC >= 0.3) {YourHotness++; }",
"Why don't you come down to my basement apartment in my mom's house and see me sometime?",
"Would you like to enjoy my laptop, I promise I don't have any viruses...",
"Would you like to enjoy my laptop, I promise I don't have any viruses…",
"You are a field in my class. You will always be protected.",
"You are my API. I want to know everything about you.",
"You are my increment operator. You make my value increase.",
"You are my initializer: without you, my life would point to nothing (null).",
"You are my loop condition. I keep coming back to you.",
"You are my methods. I am nothing without you.",
"You are my semicolon; always present in everything I do.",
"You are my superclass: you define what I can do.",
"You are so hot girl that when I first laid eyes on you, I reached a runtime error.",
"You are the Apple of my i-Mac.",
"You are the IDE of my life: I find it easier because of you.",
"You are the JDK (Java Development Kit) in my life. I won't compile without you.",
"You auto-complete me.",
"You can put a Trojan on my Hard Drive anytime",
"You defragment my life",
"You got me stuck on Caps Lock, if you know what I mean.",
"You have a trojan? hmm... I think I'll need to take a look at that backdoor.",
"You have nice syntax.",
"You look familiar. What's your Twitter handle? I think I follow you.",
"You make me want to calibrate my joystick without the latest drivers",
"You make my software turn into hardware!",
"You must be tired because you've been streaming through my RSS feed all day…",
"You must be Windows 95 because you have me so unstable.",
"You put the SPARC in my workstation.",
"You still use Internet Explorer? You must like it nice and slow.",
"You totally spiked my traffic.",
"You turn my floppy disk in to a hard drive",
"You want to learn about computers huh, you've already passed the first lesson Turning Me On",
"You're hotter then the bottom of my laptop.",
"You're making me feel like I have something in common with these pop-up ads.",
"You're so pretty, I wouldn't even need to use an Instagram filter if I took your photo.",
"You've stolen the ASCII to my heart.",
"Your beauty rivals the graphics of Call of Duty.",
"Your beauty rivals the graphics of MW3.",
"Your eyes are far more gorgeous than any source code I have ever seen.",
"Your homepage or mine?",
"YouTube Myspace and I'll Google your Yahoo!",
"Hey, my name's Microsoft. Can I crash at your place tonight?",
"Hey baby, there's an OverflowException in my pants, care to handle it for me?",
"I think my heart just lagged.",
"Baby, you make my floppy disk turn into a hard drive",
"Baby, you're the only accept state of my finite automaton",
"This must be the 8th castle because I just found my princess.",
"Are you a keyboard? Because you're my type!",
"I'm not staring, I'm just stuck in a loop.",
"Can I dereference my pointer inside your protected area?",
"You are my loop condition. I keep coming back to you.",
"I used to think love() was abstract, until you implemented it in MyHeart.",
"Are you an exception? I bet I can catch you.",
"Every function without you will always be void of love.",
"How about we do some peer-to-peer sharing? Your domain or mine?",
"You have the nicest syntax I've ever seen.",
"Roses are #FF0000, violets are #0000FF. All my base are belong to you.",
"You are the SDK in my life. I won't compile without you.",
"You are one well-defined function!",
"If you were a browser, you'd be called FireFoxy.",
"Hey girl, what's the drop rate on those pants?",
"The ladies call me Hadouken, Because I am Down right Fierce.",
"You are my initializer: without you, my life would point to nothing (null).",
"Hey baby, wanna inject my dependency?",
"If I freeze, it's not a computer virus. I was just stunned by your beauty.",
"If I was an operating system, your process would have top priority.",
"You can unzip my files anytime.",
"I need more than 140 characters to tell you how beautiful you are.",
"You must be Windows 95 because you've got me feeling so unstable.",
"You must be an angel, because your texture mapping is so divine!",
"You are my semicolon; always present in everything I do.",
"If I can't buy you a drink, at least let me fix your laptop.",
"You've stolen the ASCII to my heart.",
"Baby, you're the invariant of the algorithm of my heart.",
"You Auto-Complete me.",
"A life without you, would be like a computer without an OS.",
"Baby, you make all my binary search trees balance.",
"You make me want to calibrate my joystick without the latest drivers.",
"You are my API. I want to know everything about you.",
"Hey baby, how about you let me probe your ports, and you can dereference my pointer?",
"I'd switch to emacs for you.",
"You're hotter than a data center!",
"You compute me.",
"Press any key to continue.",
"You are my superclass: you define what I can do.",
"You are my methods. I am nothing without you.",
"Yes, that's a iPhone in my pocket, but I'm also glad to see you.",
"You have a good web-surfing stance.",
"Hey girl, want to see my Red Hat?",
"Baby if my heart were a *nix box, you'd have root access.",
"If they made you in C, you would have a pointer to my heart!",
"let me be your CSS to your HTML",
"Fork my heart because I'm ready to commit",
"I've spent so much time working with computers, you bet I know how to turn things on",
"I must be an exception because you have sure caught me.",
"Are you a double? The thought of you always floats inside my head.",
"Hey girl did u lose a timestamp coz i am pretty sure its DateTime.now();",
"Date me because I have side projects instead of side chicks",
"If I pull and push it in, know that I am already committing.",
"with all the variables in life...baby can you be my constant...",
"Are you https?? Bcz without you I'm just ://",
"Are you a function? Let me call you.",
"Girl are you CSS? Cause you got class",
"It works on my end",
"We can merge, without conflicts!",
"Are you a keyboard, cause you're my type",
"May I append my surname to your name?",
"You are my bug in my code coz i spend all my time on you",
"My object is oriented towards you.",
"Are you an exception? Let me catch you.",
"Are you a semicolon, because you totally completing me!",
"Can you be my html because i will give my body to you",
"You are my number 0",
"Me += You",
"Are you double? You always float inside my head.",
"I can't wait to inject my SQL into your application layer.",
"I always forget ; because I want to end it with you",
"Hlo r u gril?",
"Can i squeeze my hardware into your software, Without getting a virus?",
"Hey girl, is your name Truecaller? Because you're totally getting my name and number.",
"You're like the ultimate software, there's no room for upgrades.",
"I have just done a full system scan and there are definately no viruses.",
"If you were a temple i'd run all over you.",
"When I'm with you, all my layers are visible.",
"Are you a master of Powerpoint? Because I'd sure like to slide all over your deck.",
"Hey babe, are you a software update?",
"Because I'm busy right now, but let's do it tonight.",
"If you were a computer program with a bug, I would valgrind you all night long.",
"Are you a software update?, Whenever i see you, I'm like 'not now'.",
"Are you a software update? Because I'd like to update you tonight.",
"Hey girl, how about you Ruzzle up some grub?",
"Are you an Excel expert because you sure spread my sheets.",
"Are you familiar with computer science?, Cause you sure turn my software into hardware",
"Are u a computer genuis ?,Bc u are turning my software to hardware",
"Are u an IT expert?, Coz u turn my software into hardware.",
"How to find if a software engineer likes from front or back?, Just ask if you're a frontend or backend XD",
"Are you an IT technician?,  Cause you make my software go hardware",
"Hey, I'm not an IT expert, But I'm pretty sure my software just became hardwares",
"Are you a software engineer, Because you seem to be an expert in Qt!",
"When you flash your software, my floppy becomes a hard drive.",
"Hey baby, we should merge our layers.",
"Are you the hardware of my dreams?",
"Hey girl, are you a computer scientist ?, Cuz u just turned my Software into Hardware",
"Are you my driver? Because you make my life worthwhile.",
"Are you an exception? Let me catch you.",
"Are you an applet? You make me feel all GUI (gooey) inside.",
"Are your pants a compressed file? Because I'd love to unzip them!",
"You are the Apple of my i-Mac.",
"Are you an angel, because your texture mapping is divine!",
"Are you a double? The thought of you always floats inside my head.",
"Computer techs have skilled fingers if you know what I mean.",
"Can you be my private variable? I want to be the only one with access to you.",
"Is your name Google? Because you have everything I've been searching for.",
"You make my software turn into hardware!",
"Is your name Wi-fi? Because I'm really feeling a connection.",
"Are you sitting on the F5 key? Cause your ass is refreshing.",
"Want to see my HARD Disk? I promise it isn't 3.5 inches and it ain't floppy.",
"You can put a Trojan on my Hard Drive anytime.",
"You still use Internet Explorer? You must like it nice and slow.",
"I hope you're an ISO file, because I'd like to mount you.",
"My servers never go down... but I do!",
"Hi, my name's Microsoft. Can I crash at your place tonight?",
"My 'up-time' is better than BSD.",
"Are you an angel, because your texture mapping is divine!",
"You've stolen the ASCII to my heart.",
"Are you a computer keyboard? Because you're my type.",
"You got me stuck on Caps Lock, if you know what I mean.",
"If you were a web browser, you'd be called a Fire-foxy lady.",
"How about we do a little peer-to-peer saliva swapping?",
"Mind if I run a sniffer to see if your ports are open?",
"Your beauty rivals the graphics of Call of Duty.",
"You must be Windows 95 because you've got me feeling so unstable.",
"I was hoping you wouldn't block my pop-up.",
"Want to see my Red Hat?",
"If you won't let me buy you a drink, at least let me fix your laptop.",
"You put the SPARC in my workstation.",
"You're so pretty, I wouldn't even need to use an Instagram filter if I took your photo.",
"Isn't your e-mail address beautifulgirl@mydreams.com?",
"I'd switch to emacs for you.",
"What's a nice girl like you doing in a chatroom like this?",
"No, that's not a Logitech MX-100 in my pants, but thanks for noticing.",
"Nice Set of Floppies!",
"I think you could be an integral part of my project life cycle.",
"If you have an empty slot, I have the card to fill it.",
"WebMD says your love is contagious.",
"Hey, how 'bout I take off your cover and insert a bigger CPU.",
"I'd like to play on your laptop.",
"Where's the 'like' button for that smile?",
"You totally spiked my traffic.",
"You are the Apple of my i-Mac.",
"If you were an ISP I'd dial you all day long.",
"If you were an ebay auction, I'd totally 'buy it now'.",
"You have a trojan? hmm... I think I'll need to take a look at that backdoor.",
"Come to my 127.0.0.1 and I'll give you sudo access.",
"I must be using Apple maps, because I keep getting lost in your eyes.",
"I'd get a T3 to watch your streaming video.",
"I'll bet my hard drive is the biggest you've ever seen.",
"Your homepage or mine?",
"Hey Baby, Let me hack your kernel.",
"No, that's not an iPod mini in my pocket. I'm just happy to see you.",
"You auto-complete me.",
"I didn't mean to ogle you, but I'd sure like to Google you.",
"If you ever need to get rid of a trojan, don't hesitate to call me!",
"You're making me feel like I have something in common with these pop-up ads.",
"I need to hop over to Facebook for a second to change my status to smitten.",
"Roses are #ff0000, violets are #0000ff, all my base are belong to you.",
"Need me to unzip your files?",
"Are your pants a compressed file? Because I'd love to unzip them!",
"I googled your name earlier... I clicked on 'I'm Feeling Lucky.'",
"How about we go home and you handle my exception?",
"If we were connected on Linkedin, I'd endorse you all night long.",
"I wish you were Broadband, so I could get high-speed access.",
"Girl, you are hotter than the bottom of my laptop.",
"I'd ask if you come here often, but I already stalk you on FourSquare.",
"Can I do a penetration test on your back door?",
"Can you put a Trojan on my Hard Drive?",
"Hey girl, can you sit on my laptop?",
"Can I stick my flash drive in your USB port?",
"Computer techs have skilled fingers if you know what I mean.",
"You're My Compiler. My Life Program Wouldn't Start Running Without You.",
"I Want To You To Become My Private Variable So That I Will Be The Only One With Access To You.",
"I Always Thought Love Is An Abstract Class, Until You Created An Instance Of It.",
"I Leaked All Memory After I Met You.",
"Hey Beautiful Girl , You Are My .exe File.",
"Can I Become Your Personal System Annalist .",
"If You Wish Together, We Make Great Parent Classes Of Multiple Inheritance.",
"Can I De-reference My Pointer Inside Your Protected Area?",
"Are You A Global Variable , I See Your Presence Everywhere.",
"You Are My Semicolon; Always Present In Everything I Do.",
"Hey Girl You Are My Methods , Without You I Can Not Do Anything Worth.",
"No Matter How I Sort Things You Will Always Be The First.",
"My Bot Wants To Crawl All Of Your Directories.",
"You Are The Perfect Variable To Store My Love.",
"My Life Was Full Of Errors, You Came , Debugged And Compiled My Life.",
"Funny Computer Programming Pick Up Lines",
"You Had Me At Hello World.",
"Let's Flip A Coin, If Its Head You Are Mine, Tail I Am Yours.",
"You Are Line A Criminal Because You Stole My Heart.",
"How Come You Are Not On The Top Of The Christmas Tree? I Thought That's Where Stars Belonged.",
"You Are So Beautiful, You Made Me To Forget My Pick Up Line.",
"Can I Follow You? Cause My Parents Always Told Me To Follow My Dreams.",
"Are You Tired? Because You Have Been Running Through My Mind All Day.",
"Do You Have Band-aid? I Just Scraped My Knee Falling For You.",
"I Sneezed Because God Blessed Me With You.",
"Are You Wifi? Cause I Am Feeling Connection.",
"I Thought Happiness Started With An H. Why Does Mine Start With You.",
"Know What's On Menu? Me-n-u.",
"I Think I Am Suffering From A Lack Of Vitamin-u.",
"Just Smile If I Am Wrong. But Dinosaurs Still Exist Right?",
"Damn, I Forgot My Lipbalm. Can I Use Your Lips?",
"Are You A Camera? Because Whenever I See You I Smile.",
"Sorry I Forgot Your Name. Can I Call You Mine?",
"I Must Be In A Museum Because I Am Looking At Work Of Art.",
"I Hope You Know First Aid, Because You Are Taking My Breath Away.",
"You Must Be Magician,cause Whenever I Look At You Everything Just Disappears.",
"Your Hands Look Tired. Can I Hold It For You?",
"I Don't Believe In Love At First Sight But I Am Willing To Make An Exception In Your Case.",
"You Know How Else Your Hair Would Look Really Good? In My Lap.",
"My Love For You Is Like Dividing By Zero. It Cannot Be Defined.",
"Eureka! I Just Discovered Eight Wonder Of World.",
"I Think You Are Synonym For Beautiful.",
"You Are Like Kfc And I Am Like Mc Donalds. You Are So Good And I Am Lovin' It.",
"I Want To Our Love To Be Like Pi, Irrational And Never Ending.",
"Are You Cup Of Coffee? Because You Are Keeping Me Up All Night.",
"I Am Learning Important Dates In History? When Is Your Birthday?",
"I Need U To Complete The Spelling Of My Future.",
"If You Were A Drug I Would Overdose.",
"I Am A Dentist. I Fix Broken Smiles.",
"If You Were A Tweet, You Would Be My Favorite.",
"I Am Not Flirting. I Am Just Extra Nice To Someone Extra Beautiful.",
"Hey You Should Not Wear Make Up. It's Messing With The Perfection.",
"If I Were God, All Of My Angels Would Look Like You.",
"I Need You The Way A Drowning Man Needs Air.",
"Computer Geek Pick Up Lines",
"If You Were A Usb Port I'd Stick My Jump Drive Into You.",
"Trust Me, I'm User Friendly.",
"Youtube Myspace And I'll Google Your Yahoo!",
"Girl, You Are An A++.",
"You Look Familiar. What's Your Twitter Handle? I Think I Follow You.",
"My Name Is #####, And I Speak Klingon.",
"Your Homepage Or Mine?",
"Im Not Staring, Im Stuck In A Loop. (Logic: While (Girl=hot, Look))",
"Hey Baby, Let Me Hack Your Kernel.",
"“why Don't You Come Down To My Basement Apartment In My Mom's House And See Me Sometime?”",
"A Life Without You, Would Be Like A Computer Without An Os.",
"If I Was An Operating System, Your Process Would Have Top Priority.",
"I'd Like To Play On Your Laptop.",
"Be The Hard Drive Of My Dreams.",
"You Make My Software Turn Into Hardware!",
"You Must Be Windows 95 Because You Have Me So Unstable.",
"Computer Techs Have Skilled Fingers If You Know What I Mean.",
"Are You An Angel, Because Your Texture Mapping Is Divine!",
"If You Won't Let Me Buy You A Drink, At Least Let Me Fix Your Laptop.",
"I Think You Could Be An Integral Part Of My Project Life Cycle.",
"What's A Nice Girl Like You Doing In A Chat Room Like This?",
"You Got Me Stuck On Caps Lock, If You Know What I Mean.",
"Isn't Your E-mail Address Beautifulgirl@mydreams.com?",
"I'll Bet My Hard Drive Is The Biggest You've Ever Seen.",
"Want To Come See My Hard Disk? I Promise It Isn't 3.5 Inches And It Ain't Floppy.",
"How About We Go Home And You Handle My Exception?",
"If You Were An Isp I'd Dial You All Day Long.",
"If You Have An Empty Slot, I Have The Card To Fill It.",
"No, That's Not A Iphone In My Pants, But Thanks For Noticing.",
"Mind If I Run A Sniffer To See If Your Ports Are Open?",
"My 'up-time' Is Better Than Bsd.",
"I Was Hoping You Wouldn't Block My Pop-up.",
"Need Me To Unzip Your Files?",
"Your Beauty Rivals The Graphics Of Mw3.",
"You've Stolen The Ascii To My Heart.",
"You Can Put A Trojan On My Hard Drive Anytime.",
"Hey, How 'bout I Take Off Your Cover And Insert A Bigger Cpu.",
"I'd Switch To A Iphone For You.",
"Nice Set Of Floppies!",
"No, That's Not An Ipod Mini In My Pocket. I'm Just Happy To See You.",
"How About We Do A Little Peer-to-peer Saliva Swapping?",
"Want To See My Red Hat?",
"How'd You Like To Come To Myspace So I Can Twitter You With My Yahoo Until I Google On Your Facebook?",
"You Must Be Tired Because You've Been Streaming Through My Rss Feed All Day…",
"Here's My Number: 0011 0011 1011  0001 0010 1000 0101",
"I Want All Of Our Functions To Be Read/write.",
"I Think We Should Increase Our Bandwidth.",
"You Are The Jdk (Java Development Kit) In My Life. I Won't Compile Without You.",
"You Are My Superclass: You Define What I Can Do.",
"Oh Little Processer Of My Desire!",
"If You Were A Part Of My Domain, We Could Share Cookies.",
"Is Your Name Google? (Why?) Because You Have Exactly What I'm Looking For!",
"You Have Nice Syntax.",
"Hey Cutie! I Have A Processor, And If You Have An Empty Slot On Your Motherboard.",
"I Would Love To Stick My Pins Into Your Sockets.",
"No Kinky Windows Stuff.",
"Press Any Key To Continue.",
"Roses Are #ff0000, Violets Are #0000ff. All My Base Are Belong To You.",
"Phone For You, I Think It's Your Motherboard.",
"Are You An Exception? Let Me Catch You.",
"Are You My Driver? Because You Make My Life Worthwhile.",
"My Love For You Comes With No Strings Attached.",
"No Matter How I Sort Things, You'll Always Be First.",
"Hey Baby, Did You Know I Am Wearing A C-string?",
"Could I Have Your I.p.?",
"You Are A Field In My Class. You Will Always Be Protected.",
"We Can Make Beautiful .wav Files Together.",
"I Wish To Uncompress You Over *all* My Disk Space.",
"I'll Always Have Cache For You.",
"Well, If That's How You Feel, I Guess It's Time To Upgrade.",
"I Think You're My Compiler. My Life Wouldn't Start Without You.",
"My Main Method Is 'public Love Iloveyou().'",
"Baby, Let's Configure Our Hard Drives In Master And Slave Position.",
"Oh, You Found Out About My Backups, Didn't You?",
"Before You, I Was A Pc Without A Power Outlet.",
"Baby, If They Made You In Java, You'd Be The Object Of My Desire.",
"Baby You Know This Junk Isn't Usb2.0..it's Firewire!",
"Can You Be My Private Variable? I Want To Be The Only One With Access To You.",
"Well, Now You've Gone And Killed My Process.",
"Let's Interface Our Hardware.",
"You Are The Ide Of My Life: I Find It Easier Because Of You.",
"You Are My Loop Condition. I Keep Coming Back To You.",
"Hey Baby, I'm A Power Source, And You're The Kind Of Resistor I'd Like To Deliver My Load To.",
"You Are So Hot Girl That When I First Laid Eyes On You, I Reached A Runtime Error.",
"Do U Like Me? Text '1' For 'yes,' '2' For 'no.",
"I've Fully Rebooted From My Last Relationship.",
"Your Eyes Are Far More Gorgeous Than Any Source Code I Have Ever Seen.",
"Are You An Applet? You Make Me Feel All Gui (Gooey) Inside.",
"Public Class Your World Extends My World.",
"Every Once And A While Two Numbers Meet, Link, And Become Forever Binary.",
"Would You Like To Enjoy My Laptop, I Promise I Don't Have Any Viruses…",
"You Make Me Want To Calibrate My Joystick Without The Latest Drivers.",
"Nobody Turns Me On From A Cold Boot Like You.",
"Is Your Network Encrypted? Im Looking To Hack.",
"Hey Baby, Lets Turn Off Our Firewalls And Connect Our Ethernet Cable.",
"Living With You Would Be Like Living In A Virtual Reality.",
"Baby, You Over Clock My Processor.",
"Are You A Double? The Thought Of You Always Floats Inside My Head.",
"Are You A Computer Whiz… It Seems You Know How To Turn My Software To Hardware.",
"My Attraction For You Is Stronger Than The Magnetic Forces Inside Of My Hard Disk.",
"I Wish You Were Dsl So I Could Get High Speed Access.",
"We Are An Aggregation Of Classes: One Cannot Exist Without The Other.",
"You Are My Increment Operator. You Make My Value Increase.",
"You Are My Methods. I Am Nothing Without You.",
"Do You Think We Can Make It A Step More Serious And Disable Network Sharing?",
"I Can Has Da Nasty Wit U?",
"Don't Worry Honey, They Call It My Dual-channel Ram.",
"If I Were A Method, You Must Be My Parameter, Because I Will Always Need You.",
"I Output Gibberish As You Tap My Keypad.",
"Don't Worry, The First Couple Of Times It's Always Abort, Retry, Fail.",
"You Are My Api. I Want To Know Everything About You.",
"Most People Say Women Are Np-complete, But If I Get You Into Bed, I Can Solve You In Polynomial Time!",
"No Gpu In The World Could Make You Look Hotter Than You Already Are.",
"I Am A Boolean Method Whose Love Will Always Return True.",
"Our Love Routines Link Perfectly.",
"You Are My Initializer: Without You, My Life Would Point To Nothing (Null).",
"I'll Have To Try Again Tomorrow, Because You've Already Exceeded My Bandwidth.",
"I Am The Field Attribute In Your Class: I Can't Exist Unless You Do.",
"You Are My Semicolon; Always Present In Everything I Do.",
"I'm Overheating Because You're Stuck In My Head Like An Infinite Loop.",
"Baby, If They Made You In C, You Would Have A Pointer To My Heart.",
"My Love For You Is A Constant Variable: Unupdatable And Unchangeable.",
"Can You Be My Actionlistener? That Way You Notice Everything That I Do.",
"I Am A Bufferedreader. You Input Meaning Into My Life.",
"Let's Just Cut To The Chase, I Wanna Hotsync Your Pda.",
"Romantic Computer Programming Pick Up Lines",
"You're My Missing Semicolon.",
"Are You A Static Method? Cuz I'd Like To Call You Sometime Without Turning You Into An Object.",
"Are You Multi-threaded? Because You've Caused A Race Condition In My Heart.",
"I'm Gonna Pass My Function And Iterate All Over You Until You Return The Result.",
"My Love For You Is A Const, Never Changing. It's Also Global, No Bound.",
"Are You Poorly Optimized C Code? Because You're Gonna Stay In My Memory.",
"Hey Baby, If You Were Unsigned, You Would Be My Minus One",
"You're So Hot, You Make Me Prematurely Exit My For-loops.",
"You Implement Me",
"Won't Mind You Debugging All Of The Bugs In My Life",
"You Are The Bootstrap In My Html..",
"I Am Ready To Code A New World With You",
"Can I Call You Css Because I Like Your Style",
"I Must Be An Exception Because You Have Sure Caught Me.",
"My Servers Never Go Down... But I Do.",
"You're The Boot Loader To My Os, The Java To My Android, The C To My C++",
"I Used To Think Love() Was Abstract Until You Executed It In Myheart.",
"You Are Super Class,",
"You Are The Top Of The Tree,",
"You Look So Sharp,",
"You Are The ++ Of C.",
"My Heart Is An Array Of 1.",
"Hey Girl, I Will Never Delete The Pointer In My Heart To You.",
"Hey Girl , Wrap Yourself In A Try/catch And I Will Through All My Love To You."];;
      function onButtonClick() {
        const div = document.getElementById('myDiv');
        const randomString = strings[Math.floor(Math.random() * strings.length)];
        div.innerHTML = randomString;
      }

      const button = document.getElementById('myButton');
      button.addEventListener('click', onButtonClick);